version: "3.9"
services:
  web:
    build: .
    container_name: django_demo_web
    ports:
      - "5050:5050"
    environment:
      - DJANGO_SETTINGS_MODULE=config.settings
      - PYTHONUNBUFFERED=1
    restart: unless-stopped
